version = 0.1
[default.deploy.parameters]
stack_name = "rbhatiya"
resolve_s3 = true
s3_prefix = "rbhatiya"
region = "ap-southeast-2"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
disable_rollback = true
parameter_overrides = "Stage=\"dev\""
image_repositories = []
