AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31


Parameters:
  Stage:
    Type: String
    Description: Stage name to deploy resources to
    AllowedValues:
      - dev
      - stage
      - production


Globals:
  Function:
    Timeout: 30

Resources:
  SpringBootAWSLamdaFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: .
      Handler: com.rbhatiya.springbootAWSLamda.MyLambdaHandler::handleRequest
      Runtime: java17
      AutoPublishAlias: production
      SnapStart:
        ApplyOn: PublishedVersions
      Architectures:
        - x86_64
      MemorySize: 2048
      Environment:
        Variables:
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1
      Events:
        SpringbootAWSLamdaAPI:
          Type: Api
          Properties:
            Path: /api/v1/users
            Method: ANY